test:
  - changed-files:
      - any-glob-to-any-file: src/test/**

workflow:
  - changed-files:
      - any-glob-to-any-file: [ '.github/**' ,'.mergify.yml' ]

documentation:
  - changed-files:
      - any-glob-to-any-file: [ 'CHANGELOG.md' ,'LICENSE' ,'README.md' ,'QuickStart.md' ,'SECURITY.md' ,'CONTRIBUTORS.md' ,'CONTRIBUTING.md' ]

dependencies:
  - changed-files:
      - any-glob-to-any-file: pom.xml

automerge:
  - changed-files:
      - any-glob-to-any-file: [ 'README.md' ,'CHANGELOG.md' ,'QuickStart.md' ,'CONTRIBUTORS.md' ]
